name: capstone2
channels:
    - conda-forge
    - default
    - anaconda
    - derickl
dependencies:
    - eli5
    - numpy
    - jupyter
    - jupyterlab
    - jupyter_contrib_nbextensions
    - keras
    - matplotlib
    - numpy
    - pip>=9.0.0
    - pandas
    - pydotplus
    - python>=3.7
    - pygraphviz
    - pytest
    - pytest-datadir
    - scikit-learn
    - scipy
    - seaborn
    - shap
    - tensorflow>=1.0.0
    - pip:
        - virtualenvwrapper
