name: capstone2
channels:
    - conda-forge
    - default
    - anaconda
    - derickl
dependencies:
    - numpy
    - jupyter
    - jupyterlab
    - keras
    - matplotlib
    - numpy
    - pip>=9.0.0
    - pandas
    - python>=3.7
    - pygraphviz
    - scikit-learn
    - scipy
    - seaborn
    - shap
    - tensorflow>=1.0.0
    - pip:
        - eli5
        - skater
        - virtualenvwrapper
